"""Real configuration transactions in temporary trees; no host DNS changes."""
import configparser
import ipaddress
import json
import os
from pathlib import Path
import sys
import tempfile
import threading
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "service"))
from omarchy_kids.school_mode import config, family_dns as dns
import test_free_time as fixtures


class Resolver(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(); self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.config, self.etc = self.root / "config", self.root / "etc"
        self.config.mkdir(); self.etc.mkdir()
        self.normal = "# Generated by NetworkManager\nnameserver 192.168.1.1\n"
        (self.etc / "resolv.conf").write_text(self.normal)
        self.calls = []
        self.other_nm = ""
        self.fail_next_restart = False
        self.resolved_override = ""
        self.integration = dns.Integration(self.config, self.etc, self.run_command)

    def run_command(self, *args):
        self.calls.append(args)
        enabled = (self.etc / "NetworkManager/conf.d" / dns.NAME).read_text() == dns.NM_ON
        if args[:2] == ("/usr/bin/systemctl", "is-active"):
            return "active\nactive\n"
        if args[0] == "/usr/bin/NetworkManager":
            if enabled:
                # NetworkManager.conf uses comma-separated lists, unlike its
                # .nmconnection keyfiles. Reject a resolver list NM cannot read.
                parsed = configparser.ConfigParser()
                parsed.read_string((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text())
                addresses = [ipaddress.ip_address(value.strip())
                             for value in parsed["global-dns-domain-*"]["servers"].split(",")]
                self.assertEqual({str(ip) for ip in addresses},
                                 {"1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"})
            return (dns.NM_ON if enabled else "[main]\ndns=systemd-resolved\n") + self.other_nm
        if args[0] == "/usr/bin/nmcli":
            (self.etc / "resolv.conf").write_text(
                "".join(f"nameserver {ip}\n" for ip in dns.SERVERS) if enabled else self.normal)
        if args[:2] == ("/usr/bin/systemctl", "restart") and self.fail_next_restart:
            self.fail_next_restart = False
            raise ValueError("fixture resolver restart failed")
        if args[0] == "/usr/bin/resolvectl":
            return "Global: " + " ".join(dns.SERVERS) + "\nLink 2 (wlan0): " + self.resolved_override + "\n"
        return ""

    def test_enable_disable_and_removal_preserve_network_profiles_and_unrelated_policies(self):
        self.integration.install()
        profile = self.etc / "NetworkManager/system-connections/home.nmconnection"
        profile.parent.mkdir(); profile.write_text("[ipv4]\ndns=192.168.1.1;\nmethod=auto\n")
        unrelated = self.etc / "chromium/policies/managed/administrator.json"
        unrelated.write_text('{"HomepageLocation":"https://school.example"}')
        before = profile.read_bytes(), unrelated.read_bytes()
        self.assertFalse(self.calls, "Setup must leave DNS unchanged until the parent enables it")
        self.assertTrue(self.integration.ready())
        self.integration.apply(True)
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[1])
            self.assertEqual(path.stat().st_mode & 0o777, 0o644)
            self.assertEqual(path.parent.stat().st_mode & 0o755, 0o755)
        self.assertEqual(json.loads(self.integration.receipt.read_text())["pending"], False)
        self.integration.install()  # Upgrade leaves an enabled resolver enabled.
        self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.NM_ON)
        self.integration.apply(False)
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.assertEqual((profile.read_bytes(), unrelated.read_bytes()), before)
        count = len(self.calls)
        self.integration.apply(False)
        self.assertEqual(len(self.calls), count, "Off must not restart DNS on every tick")
        self.integration.remove()
        self.assertFalse(any(p.exists() for p in dns.files(self.etc)))
        self.assertEqual((profile.read_bytes(), unrelated.read_bytes()), before)
        self.assertNotIn(("/usr/bin/systemctl", "restart", "NetworkManager.service"), self.calls)

    def test_reload_failure_rolls_back_and_a_retry_succeeds(self):
        self.integration.install()
        self.fail_next_restart = True
        with self.assertRaisesRegex(ValueError, "restart failed"):
            self.integration.apply(True)
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[0])
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.integration.apply(True)
        self.integration.remove()
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)

    def test_existing_global_dns_and_secure_browser_dns_are_not_overwritten(self):
        self.integration.install()
        self.other_nm = "[global-dns-domain-*]\nservers=192.168.1.1\n"
        with self.assertRaisesRegex(ValueError, "already has global"):
            self.integration.apply(True)
        self.other_nm = ""
        other = self.etc / "chromium/policies/managed/administrator.json"
        other.write_text('{"DnsOverHttpsMode":"secure"}')
        with self.assertRaisesRegex(ValueError, "Browser DNS policy conflict"):
            self.integration.apply(True)
        self.assertEqual(other.read_text(), '{"DnsOverHttpsMode":"secure"}')
        self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.OFF)

    def test_unfiltered_ipv6_or_later_overrides_roll_back(self):
        self.integration.install()
        self.resolved_override = "2001:db8::53"
        with self.assertRaisesRegex(ValueError, "resolver configuration overrides"):
            self.integration.apply(True)
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.resolved_override = ""
        self.other_nm = "[main]\ndns=none\n"
        with self.assertRaisesRegex(ValueError, "Another DNS manager"):
            self.integration.apply(True)

    def test_unknown_files_symlinks_and_local_edits_stop_setup_or_removal(self):
        target = next(iter(dns.files(self.etc)))
        target.parent.mkdir(parents=True); target.write_text("administrator config")
        with self.assertRaisesRegex(ValueError, "collision"):
            self.integration.install()
        target.unlink()
        self.integration.install()
        target.write_text("administrator edit")
        with self.assertRaisesRegex(ValueError, "edited"):
            self.integration.remove()
        self.assertEqual(target.read_text(), "administrator edit")
        target.unlink(); target.symlink_to(self.etc / "resolv.conf")
        with self.assertRaisesRegex(ValueError, "owned"):
            self.integration.install()

    def test_foreign_resolv_symlink_is_not_replaced(self):
        self.integration.install()
        resolv = self.etc / "resolv.conf"
        resolv.unlink(); resolv.symlink_to("/run/another-resolver/resolv.conf")
        with self.assertRaisesRegex(ValueError, "Another DNS manager"):
            self.integration.apply(True)
        self.assertEqual(os.readlink(resolv), "/run/another-resolver/resolv.conf")

    def test_interrupted_disable_reloads_even_when_files_are_already_off(self):
        self.integration.install()
        receipt = json.loads(self.integration.receipt.read_text()); receipt["pending"] = True
        self.integration.receipt.write_text(json.dumps(receipt))
        self.integration.apply(False)
        self.assertIn(("/usr/bin/nmcli", "general", "reload", "conf", "dns-full"), self.calls)
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_default_and_patch_validation(self):
        self.assertFalse(config.sanitize({})["family_dns_enabled"])
        for bad in (1, "true", None, [], {}):
            self.assertFalse(config.valid_patch({"family_dns_enabled": bad}))
        self.assertTrue(config.valid_patch({"family_dns_enabled": True}))


class Service(unittest.TestCase):
    setUp = fixtures.ServiceTests.setUp
    start_daemon = fixtures.ServiceTests.start_daemon
    request = fixtures.ServiceTests.request
    parent = fixtures.ServiceTests.parent

    def prepare(self):
        manager = self.daemon.services["school"].family_dns
        integration = manager.integration
        integration.etc.mkdir()
        integration.install()
        calls = []
        self.context.enter_context(patch.object(integration, "apply", side_effect=lambda enabled: calls.append(enabled)))
        self.addCleanup(self.wait, manager)
        return manager, calls

    def wait(self, manager):
        if manager.worker:
            manager.worker.join(5)
            self.assertFalse(manager.worker.is_alive())

    def test_only_parent_can_toggle_and_both_modes_and_profiles_share_dns(self):
        manager, calls = self.prepare()
        change = {"family_dns_enabled": True}
        self.assertFalse(self.request({"cmd": "config.patch", "patch": change})["ok"])
        self.assertTrue(self.parent(cmd="config.patch", patch=change)["ok"])
        self.wait(manager)
        self.assertEqual(calls, [True])
        for mode in ("free", "school", "free", "school"):
            self.parent(cmd="mode.set", mode=mode)
            self.assertTrue(self.request({"cmd": "status"})["websites"]["familyDns"]["active"])
        self.assertEqual(calls, [True], "Mode changes must never remove or restart Family DNS")
        self.assertFalse(self.request({"cmd": "status"})["websites"]["enabled"])
        saved = self.parent(cmd="config.get")["config"]
        self.assertTrue(saved["family_dns_enabled"])
        self.assertTrue(all("family_dns_enabled" not in p for p in saved["profiles"].values()))
        self.assertTrue(self.parent(cmd="config.patch", patch={"family_dns_enabled": False})["ok"])
        self.wait(manager)
        self.assertEqual(calls, [True, False])

    def test_missing_setup_is_an_actionable_error_without_saving(self):
        result = self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.assertEqual(result["error"], "family_dns_setup")
        self.assertFalse(self.parent(cmd="config.get")["config"]["family_dns_enabled"])

    def test_network_delay_does_not_block_timer_and_errors_are_published(self):
        manager, calls = self.prepare()
        started, finish = threading.Event(), threading.Event()
        self.addCleanup(finish.set)
        def slow_apply(enabled):
            started.set()
            finish.wait(5)
            raise ValueError("fixture DNS unavailable")
        manager.integration.apply.side_effect = slow_apply
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.assertTrue(started.wait(2))
        self.assertTrue(self.request({"cmd": "status"})["websites"]["familyDns"]["applying"])
        self.parent(cmd="mode.set", mode="free")
        self.now += 1800
        self.daemon.refresh(self.now)
        self.lock_call.assert_called_once()
        finish.set(); self.wait(manager)
        self.daemon.refresh(self.now)
        status = self.request({"cmd": "status"})["websites"]["familyDns"]
        self.assertFalse(status["active"])
        self.assertEqual(status["error"], "fixture DNS unavailable")

    def test_reboot_and_disabling_last_enrollment(self):
        manager, calls = self.prepare()
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.wait(manager)
        self.start_daemon()
        manager = self.daemon.services["school"].family_dns
        self.context.enter_context(patch.object(manager.integration, "apply", side_effect=lambda enabled: calls.append(enabled)))
        self.addCleanup(self.wait, manager)
        self.daemon.refresh(self.now); self.wait(manager)
        self.assertEqual(calls, [True, True])
        self.daemon.dispatch(0, {"scope": "school", "cmd": "users.set", "user": "linnea", "enabled": False})
        self.wait(manager)
        self.assertEqual(calls, [True, True, False])


if __name__ == "__main__":
    unittest.main()
