"""Real configuration transactions in temporary trees; no host DNS changes."""
import configparser
import ipaddress
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import threading
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "service"))
from omarchy_kids.school_mode import config, family_dns as dns
import test_free_time as fixtures


class Resolver(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory(); self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        self.config, self.etc = self.root / "config", self.root / "etc"
        self.config.mkdir(); self.etc.mkdir()
        self.normal = "# Generated by NetworkManager\nnameserver 192.168.1.1\n"
        (self.etc / "resolv.conf").write_text(self.normal)
        self.calls = []
        self.other_nm = ""
        self.fail_next_restart = False
        self.inactive = False
        self.resolved_override = ""
        self.global_override = ""
        self.resolved_output = None
        self.link_names = {2: "wlan0"}
        self.normal_link_dns = {2: ["192.168.1.1"]}
        self.link_dns = {index: list(servers) for index, servers in self.normal_link_dns.items()}
        self.nm_managed = {"wlan0"}
        self.fail_clear = None
        self.integration = dns.Integration(self.config, self.etc, self.run_command)

    def run_command(self, *args):
        self.calls.append(args)
        written = (self.etc / "NetworkManager/conf.d" / dns.NAME).read_text()
        enabled = "[global-dns-domain-*]" in written
        if args[:2] == ("/usr/bin/systemctl", "is-active"):
            if self.inactive:
                # Exit status 3 with both states on stdout and nothing on stderr.
                raise ValueError("Family DNS command failed (/usr/bin/systemctl is-active): inactive inactive")
            return "active\nactive\n"
        if args[0] == "/usr/bin/NetworkManager":
            if enabled:
                # NetworkManager.conf uses comma-separated lists, unlike its
                # .nmconnection keyfiles. Reject a resolver list NM cannot read.
                parsed = configparser.ConfigParser()
                parsed.read_string((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text())
                addresses = [ipaddress.ip_address(value.strip())
                             for value in parsed["global-dns-domain-*"]["servers"].split(",")]
                self.assertEqual({str(ip) for ip in addresses},
                                 {"1.1.1.3", "1.0.0.3", "2606:4700:4700::1113", "2606:4700:4700::1003"})
            return (written if enabled else "[main]\ndns=systemd-resolved\n") + self.other_nm
        if args[:3] == ("/usr/bin/nmcli", "--get-values", "GENERAL.NM-MANAGED"):
            self.assertEqual(args[3:5], ("device", "show"))
            return "yes\n" if args[5] in self.nm_managed else "no\n"
        if args[:3] == ("/usr/bin/nmcli", "general", "reload"):
            # nmcli accepts a single flags argument; a second positional flag
            # is an error, even though the manual writes the synopsis flags….
            if len(args) > 4:
                raise ValueError("Error: extra argument 'dns-full'")
            (self.etc / "resolv.conf").write_text(
                "".join(f"nameserver {ip}\n" for ip in dns.SERVERS) if enabled else self.normal)
            if not enabled:
                # NetworkManager republishes the connection's current DNS when
                # its resolved plugin is restored. No stale snapshot is replayed.
                for index, servers in self.normal_link_dns.items():
                    if self.link_names[index] in self.nm_managed:
                        self.link_dns[index] = list(servers)
        if args[:2] == ("/usr/bin/systemctl", "restart") and self.fail_next_restart:
            self.fail_next_restart = False
            raise ValueError("fixture resolver restart failed")
        if args[0] == "/usr/bin/resolvectl":
            if len(args) == 4:
                self.assertEqual((args[1], args[3]), ("dns", ""))
                index = int(args[2])
                if self.fail_clear == index:
                    raise ValueError("fixture DNS clear failed")
                self.link_dns[index] = []
                return ""
            if self.resolved_output is not None:
                return self.resolved_output
            # Like resolved, retain per-link DNS across a service restart.
            # A resolved drop-in sorted after ours keeps its server in the global
            # list. Nothing shows that until Family DNS has been written.
            result = "Global: " + (" ".join([*dns.SERVERS, self.global_override]).strip() if enabled else "") + "\n"
            for index, servers in self.link_dns.items():
                result += f"Link {index} ({self.link_names[index]}): " + "\n        ".join(servers) + "\n"
            return result + "Link 99 (external0): " + self.resolved_override + "\n"
        return ""

    def test_enable_disable_and_removal_preserve_network_profiles_and_unrelated_policies(self):
        self.integration.install()
        profile = self.etc / "NetworkManager/system-connections/home.nmconnection"
        profile.parent.mkdir(); profile.write_text("[ipv4]\ndns=192.168.1.1;\nmethod=auto\n")
        unrelated = self.etc / "chromium/policies/managed/administrator.json"
        unrelated.write_text('{"HomepageLocation":"https://school.example"}')
        before = profile.read_bytes(), unrelated.read_bytes()
        self.assertFalse(self.calls, "Setup must leave DNS unchanged until the parent enables it")
        self.assertTrue(self.integration.ready())
        self.integration.apply(True)
        self.assertEqual(self.link_dns[2], [], "Persisted DHCP DNS must not bypass Family DNS")
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[1])
            self.assertEqual(path.stat().st_mode & 0o777, 0o644)
            self.assertEqual(path.parent.stat().st_mode & 0o755, 0o755)
        self.assertEqual(json.loads(self.integration.receipt.read_text())["pending"], False)
        self.integration.install()  # Upgrade leaves an enabled resolver enabled.
        self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.NM_ON)
        self.integration.apply(False)
        self.assertEqual(self.link_dns[2], ["192.168.1.1"])
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.assertEqual((profile.read_bytes(), unrelated.read_bytes()), before)
        count = len(self.calls)
        self.integration.apply(False)
        self.assertEqual(len(self.calls), count, "Off must not restart DNS on every tick")
        self.integration.remove()
        self.assertFalse(any(p.exists() for p in dns.files(self.etc)))
        self.assertEqual((profile.read_bytes(), unrelated.read_bytes()), before)
        self.assertNotIn(("/usr/bin/systemctl", "restart", "NetworkManager.service"), self.calls)

    def test_all_managed_links_clear_ipv4_and_ipv6_and_restore_current_network_dns(self):
        self.integration.install()
        self.link_names[3] = "eth0"
        self.nm_managed.add("eth0")
        self.link_dns[3] = ["192.168.2.1", "fe80::1%3"]
        self.normal_link_dns[3] = list(self.link_dns[3])
        self.integration.apply(True)
        self.assertEqual(self.link_dns, {2: [], 3: []})
        # A different Wi-Fi network while enabled must regain its own DNS.
        self.normal_link_dns[2] = ["192.168.5.1", "2001:db8::53"]
        self.integration.apply(False)
        self.assertEqual(self.link_dns, self.normal_link_dns)

    def test_unmanaged_router_is_not_silently_allowed_or_cleared(self):
        self.integration.install()
        self.nm_managed.clear()
        with self.assertRaisesRegex(ValueError, r"wlan0 uses its own DNS \(192\.168\.1\.1\), set outside NetworkManager") as failure:
            self.integration.apply(True)
        self.assertEqual(self.link_dns[2], ["192.168.1.1"])
        self.assertFalse(any(call[0] == "/usr/bin/resolvectl" and len(call) == 4 for call in self.calls))
        self.assert_dns_untouched(failure.exception)

    def assert_dns_untouched(self, error):
        """A conflict visible beforehand must not cost a resolver restart."""
        self.assertNotIsInstance(error, dns.Disrupted)
        self.assertFalse([call for call in self.calls if call[:2] == ("/usr/bin/systemctl", "restart")
                          or call[:3] == ("/usr/bin/nmcli", "general", "reload")])
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[0])
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_another_tools_link_and_delegate_dns_are_reported_before_any_reload(self):
        self.integration.install()
        self.resolved_override = "100.100.100.100"
        with self.assertRaisesRegex(ValueError, r"external0 uses its own DNS \(100\.100\.100\.100\)") as failure:
            self.integration.apply(True)
        self.assert_dns_untouched(failure.exception)
        self.assertEqual(self.link_dns[2], ["192.168.1.1"], "The home router's DNS must not be cleared for nothing")
        self.resolved_output = "Global:\nLink 2 (wlan0): 192.168.1.1\nDelegate corp: 10.0.0.53\n"
        with self.assertRaisesRegex(ValueError, r"Delegate corp uses its own DNS \(10\.0\.0\.53\)") as failure:
            self.integration.apply(True)
        self.assert_dns_untouched(failure.exception)

    def test_failed_clear_restores_dns_on_previously_cleared_links(self):
        self.integration.install()
        self.link_names[3] = "eth0"
        self.nm_managed.add("eth0")
        self.link_dns[3] = self.normal_link_dns[3] = ["192.168.2.1"]
        self.fail_clear = 3
        with self.assertRaisesRegex(ValueError, "DNS clear failed"):
            self.integration.apply(True)
        self.assertIn(("/usr/bin/resolvectl", "dns", "2", ""), self.calls)
        self.assertEqual(self.link_dns, self.normal_link_dns)
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[0])
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_global_router_setting_remains_a_conflict(self):
        self.integration.install()
        self.resolved_output = "Global: " + " ".join(dns.SERVERS) + " 192.168.1.1\n"
        with self.assertRaisesRegex(ValueError, "additional servers: 192.168.1.1"):
            self.integration.apply(True)
        self.assertFalse(any(call[0] == "/usr/bin/resolvectl" and len(call) == 4 for call in self.calls))

    def test_reload_failure_rolls_back_and_a_retry_succeeds(self):
        self.integration.install()
        self.fail_next_restart = True
        with self.assertRaisesRegex(ValueError, "restart failed"):
            self.integration.apply(True)
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[0])
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.integration.apply(True)
        self.integration.remove()
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)

    def test_wrapped_resolvectl_output_with_server_names_enables_and_restores(self):
        self.integration.install()
        self.resolved_output = (
            "Global: 1.1.1.3#family.cloudflare-dns.com 1.0.0.3#family.cloudflare-dns.com\n"
            "        2606:4700:4700::1113#family.cloudflare-dns.com\n"
            "        2606:4700:4700::1003#family.cloudflare-dns.com\n"
            "Link 2 (wlan0):\nLink 3 (docker0):\n")
        self.integration.apply(True)
        self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.NM_ON)
        self.integration.apply(False)
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)

    def test_wrapped_unfiltered_ipv6_remains_a_real_conflict_and_restores(self):
        self.integration.install()
        self.resolved_output = (
            "Global: 1.1.1.3 1.0.0.3 2606:4700:4700::1113 2606:4700:4700::1003\n"
            "Link 99 (external0):\n        2001:db8::53\n")
        with self.assertRaisesRegex(ValueError, "2001:db8::53") as failure:
            self.integration.apply(True)
        self.assertNotIn("restoration also failed", str(failure.exception))
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_command_failures_preserve_the_action_and_stderr(self):
        failure = subprocess.CalledProcessError(2, ["/usr/bin/nmcli", "general", "reload", "conf", "dns-full"],
                                                stderr="Error: extra argument 'dns-full'\n")
        with patch.object(dns.subprocess, "run", side_effect=failure):
            with self.assertRaisesRegex(ValueError, "extra argument 'dns-full'"):
                dns.command("/usr/bin/nmcli", "general", "reload", "conf", "dns-full")
        silent = subprocess.CalledProcessError(3, ["/usr/bin/systemctl", "is-active"], output="inactive\ninactive\n", stderr="")
        with patch.object(dns.subprocess, "run", side_effect=silent):
            with self.assertRaisesRegex(ValueError, "inactive inactive"):
                dns.command("/usr/bin/systemctl", "is-active", "NetworkManager.service")

    def test_existing_global_dns_and_secure_browser_dns_are_not_overwritten(self):
        self.integration.install()
        self.other_nm = "[global-dns-domain-*]\nservers=192.168.1.1\n"
        with self.assertRaisesRegex(ValueError, "already has global"):
            self.integration.apply(True)
        self.other_nm = ""
        other = self.etc / "chromium/policies/managed/administrator.json"
        other.write_text('{"DnsOverHttpsMode":"secure"}')
        with self.assertRaisesRegex(ValueError, "Browser DNS policy conflict"):
            self.integration.apply(True)
        self.assertEqual(other.read_text(), '{"DnsOverHttpsMode":"secure"}')
        self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.OFF)

    def test_unfiltered_ipv6_or_later_overrides_roll_back(self):
        self.integration.install()
        self.global_override = "2001:db8::53"
        with self.assertRaisesRegex(dns.Disrupted, "additional servers: 2001:db8::53"):
            self.integration.apply(True)
        self.assertIn(("/usr/bin/resolvectl", "dns", "2", ""), self.calls)
        self.assertEqual(self.link_dns[2], ["192.168.1.1"], "Failure must restore the cleared router DNS")
        self.assertEqual((self.etc / "resolv.conf").read_text(), self.normal)
        self.global_override = ""
        self.other_nm = "[main]\ndns=none\n"
        with self.assertRaisesRegex(ValueError, "Another DNS manager"):
            self.integration.apply(True)

    def test_unknown_files_symlinks_and_local_edits_stop_setup_or_removal(self):
        target = next(iter(dns.files(self.etc)))
        target.parent.mkdir(parents=True); target.write_text("administrator config")
        with self.assertRaisesRegex(ValueError, "collision"):
            self.integration.install()
        target.unlink()
        self.integration.install()
        target.write_text("administrator edit")
        with self.assertRaisesRegex(ValueError, "edited"):
            self.integration.remove()
        self.assertEqual(target.read_text(), "administrator edit")
        target.unlink(); target.symlink_to(self.etc / "resolv.conf")
        with self.assertRaisesRegex(ValueError, "owned"):
            self.integration.install()

    def test_foreign_resolv_symlink_is_not_replaced(self):
        self.integration.install()
        resolv = self.etc / "resolv.conf"
        resolv.unlink(); resolv.symlink_to("/run/another-resolver/resolv.conf")
        with self.assertRaisesRegex(ValueError, "Another DNS manager"):
            self.integration.apply(True)
        self.assertEqual(os.readlink(resolv), "/run/another-resolver/resolv.conf")

    def test_interrupted_disable_reloads_even_when_files_are_already_off(self):
        self.integration.install()
        receipt = json.loads(self.integration.receipt.read_text()); receipt["pending"] = True
        self.integration.receipt.write_text(json.dumps(receipt))
        self.integration.apply(False)
        self.assertIn(("/usr/bin/nmcli", "general", "reload", "conf"), self.calls)
        self.assertIn(("/usr/bin/nmcli", "general", "reload", "dns-full"), self.calls)
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_setup_upgrades_service_4_4_2_files_while_family_dns_stays_on(self):
        self.integration.install()
        self.integration.apply(True)
        # As written by 4.4.0-4.4.2: a path-only receipt and no DNS-over-TLS line.
        resolved = self.etc / "systemd/resolved.conf.d" / dns.NAME
        resolved.write_text(dns.RESOLVED_INHERIT)
        self.integration.receipt.write_text(json.dumps(
            {"identity": dns.IDENTITY, "files": [str(p) for p in dns.files(self.etc)], "pending": False}) + "\n")
        self.integration.receipt.chmod(0o600)
        self.calls.clear()
        self.integration.install()
        self.assertFalse(self.calls, "Setup itself never reloads DNS")
        self.assertEqual(resolved.read_text(), dns.RESOLVED_INHERIT, "Upgrade leaves an enabled resolver enabled")
        receipt = json.loads(self.integration.receipt.read_text())
        self.assertEqual(receipt["files"][str(resolved)], [dns.digest(dns.RESOLVED_INHERIT)])
        self.assertTrue(self.integration.ready())
        self.integration.apply(True)  # The restarted service adopts this release's text.
        self.assertEqual(resolved.read_text(), dns.RESOLVED_ON)
        self.assertEqual(self.link_dns[2], [])
        self.integration.remove()
        self.assertFalse(any(p.exists() for p in dns.files(self.etc)))
        self.assertEqual(self.link_dns[2], ["192.168.1.1"])

    def test_a_later_release_can_change_its_texts_and_files_without_blocking_setup(self):
        self.integration.install()
        self.integration.apply(True)
        chrome = self.etc / "opt/chrome/policies/managed" / dns.POLICY_NAME
        brave = self.etc / "brave/policies/managed" / dns.POLICY_NAME
        current = dns.files

        def later(etc):
            result = {path: (off + "# later\n" if path.suffix == ".conf" else off, on + ("# later\n" if path.suffix == ".conf" else ""), ())
                      for path, (off, on, _) in current(etc).items() if path != chrome}
            return {**result, brave: (dns.POLICY_OFF, dns.POLICY_ON, ())}

        with patch.object(dns, "files", later):
            upgraded = dns.Integration(self.config, self.etc, self.run_command)
            self.calls.clear()
            upgraded.install()
            self.assertFalse(self.calls)
            self.assertFalse(chrome.exists(), "A file this release no longer owns is released")
            self.assertEqual(brave.read_text(), dns.POLICY_OFF)
            self.assertEqual(set(json.loads(upgraded.receipt.read_text())["files"]), {str(p) for p in later(self.etc)})
            self.assertEqual((self.etc / "NetworkManager/conf.d" / dns.NAME).read_text(), dns.NM_ON)
            upgraded.apply(True)
            for path, values in later(self.etc).items():
                self.assertEqual(path.read_text(), values[1])
            upgraded.install()  # Rerunning setup stays possible afterwards.
            # Ownership still means unedited: digests never adopt someone else's text.
            brave.write_text('{"DnsOverHttpsMode":"secure"}')
            with self.assertRaisesRegex(ValueError, "edited"):
                upgraded.install()
            brave.write_text(dns.POLICY_ON)
            upgraded.remove()
            self.assertFalse(any(p.exists() for p in later(self.etc)))

    def test_receipts_naming_foreign_paths_are_refused(self):
        self.integration.install()
        for paths in ([str(self.root / "elsewhere" / dns.NAME)], [str(self.etc / "NetworkManager/NetworkManager.conf")],
                      [str(self.etc / "x/../../outside" / dns.NAME)], {str(self.etc / dns.NAME): "digest"}, "files", None):
            self.integration.receipt.write_text(json.dumps({"identity": dns.IDENTITY, "files": paths, "pending": False}))
            self.integration.receipt.chmod(0o600)
            with self.assertRaisesRegex(ValueError, "Unknown Family DNS installation receipt"):
                self.integration.plan()

    def test_working_family_dns_is_rechecked_without_restarting_the_resolver(self):
        self.integration.install()
        self.integration.apply(True)
        disruptive = lambda: [call for call in self.calls if call[:2] == ("/usr/bin/systemctl", "restart")
                              or call[:3] == ("/usr/bin/nmcli", "general", "reload") or (call[0] == "/usr/bin/resolvectl" and len(call) == 4)]
        self.calls.clear()
        self.integration.apply(True)  # Every boot and service restart.
        self.assertEqual(disruptive(), [])
        self.assertTrue(self.calls, "Its configuration is still verified")
        # DNS that returned to a link, or an interrupted change, gets the full treatment.
        self.link_dns[2] = ["192.168.1.1"]
        self.integration.apply(True)
        self.assertEqual(self.link_dns[2], [])
        self.assertIn(("/usr/bin/systemctl", "restart", "systemd-resolved.service"), disruptive())
        receipt = json.loads(self.integration.receipt.read_text()); receipt["pending"] = True
        self.integration.receipt.write_text(json.dumps(receipt)); self.calls.clear()
        self.integration.apply(True)
        self.assertIn(("/usr/bin/systemctl", "restart", "systemd-resolved.service"), disruptive())
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_omarchys_own_dns_choice_is_named_with_its_fix(self):
        self.integration.install()
        self.other_nm = "[global-dns]\n[global-dns-domain-*]\nservers=1.1.1.1,1.0.0.1\n"
        (self.etc / "NetworkManager/conf.d/20-omarchy-dns.conf").write_text(self.other_nm)
        with self.assertRaisesRegex(ValueError, "omarchy dns DHCP") as failure:
            self.integration.apply(True)
        self.assert_dns_untouched(failure.exception)

    def test_stopped_services_and_unreadable_policies_are_explained(self):
        self.integration.install()
        self.inactive = True
        with self.assertRaisesRegex(ValueError, "needs NetworkManager and systemd-resolved running") as failure:
            self.integration.apply(True)
        self.assert_dns_untouched(failure.exception)
        self.inactive = False
        other = self.etc / "chromium/policies/managed/broken.json"
        other.write_text("{not json")
        with self.assertRaisesRegex(ValueError, "Cannot inspect the browser policy .*broken.json") as failure:
            self.integration.apply(True)
        self.assert_dns_untouched(failure.exception)
        self.assertEqual(other.read_text(), "{not json")

    def test_dns_over_tls_is_opportunistic_unless_an_administrator_requires_it(self):
        self.integration.install()
        resolved = self.etc / "systemd/resolved.conf.d" / dns.NAME
        main = self.etc / "systemd/resolved.conf"
        main.write_text("[Resolve]\nDNSOverTLS=no\n")  # Omarchy's DHCP choice.
        self.integration.apply(True)
        self.assertEqual(resolved.read_text(), dns.RESOLVED_ON)
        self.assertIn("DNSOverTLS=opportunistic\n", resolved.read_text())
        self.integration.apply(False)
        self.assertEqual(main.read_text(), "[Resolve]\nDNSOverTLS=no\n")
        (resolved.parent / "50-administrator.conf").write_text("[Resolve]\n DNSOverTLS = yes\n")
        self.integration.apply(True)
        self.assertNotIn("DNSOverTLS", resolved.read_text(), "A required TLS setting is inherited, never relaxed")
        self.calls.clear()
        self.integration.apply(True)
        self.assertNotIn(("/usr/bin/systemctl", "restart", "systemd-resolved.service"), self.calls)
        self.integration.remove()

    def test_an_unexpected_failure_still_restores_dns(self):
        self.integration.install()
        original = self.integration.verify
        self.integration.verify = lambda: {}["missing"]
        with self.assertRaisesRegex(dns.Disrupted, "KeyError"):
            self.integration.apply(True)
        self.integration.verify = original
        for path, values in dns.files(self.etc).items():
            self.assertEqual(path.read_text(), values[0])
        self.assertEqual(self.link_dns[2], ["192.168.1.1"])
        self.assertFalse(json.loads(self.integration.receipt.read_text())["pending"])

    def test_default_and_patch_validation(self):
        self.assertFalse(config.sanitize({})["family_dns_enabled"])
        for bad in (1, "true", None, [], {}):
            self.assertFalse(config.valid_patch({"family_dns_enabled": bad}))
        self.assertTrue(config.valid_patch({"family_dns_enabled": True}))


class Service(unittest.TestCase):
    setUp = fixtures.ServiceTests.setUp
    start_daemon = fixtures.ServiceTests.start_daemon
    request = fixtures.ServiceTests.request
    parent = fixtures.ServiceTests.parent

    def prepare(self):
        manager = self.daemon.services["school"].family_dns
        integration = manager.integration
        integration.etc.mkdir()
        integration.install()
        calls = []
        self.context.enter_context(patch.object(integration, "apply", side_effect=lambda enabled: calls.append(enabled)))
        self.addCleanup(self.wait, manager)
        return manager, calls

    def wait(self, manager):
        if manager.worker:
            manager.worker.join(5)
            self.assertFalse(manager.worker.is_alive())

    def test_only_parent_can_toggle_and_both_modes_and_profiles_share_dns(self):
        manager, calls = self.prepare()
        change = {"family_dns_enabled": True}
        self.assertFalse(self.request({"cmd": "config.patch", "patch": change})["ok"])
        self.assertTrue(self.parent(cmd="config.patch", patch=change)["ok"])
        self.wait(manager)
        self.assertEqual(calls, [True])
        for mode in ("free", "school", "free", "school"):
            self.parent(cmd="mode.set", mode=mode)
            self.assertTrue(self.request({"cmd": "status"})["websites"]["familyDns"]["active"])
        self.assertEqual(calls, [True], "Mode changes must never remove or restart Family DNS")
        self.assertFalse(self.request({"cmd": "status"})["websites"]["enabled"])
        saved = self.parent(cmd="config.get")["config"]
        self.assertTrue(saved["family_dns_enabled"])
        self.assertTrue(all("family_dns_enabled" not in p for p in saved["profiles"].values()))
        self.assertTrue(self.parent(cmd="config.patch", patch={"family_dns_enabled": False})["ok"])
        self.wait(manager)
        self.assertEqual(calls, [True, False])

    def test_missing_setup_is_an_actionable_error_without_saving(self):
        result = self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.assertEqual(result["error"], "family_dns_setup")
        self.assertFalse(self.parent(cmd="config.get")["config"]["family_dns_enabled"])

    def test_network_delay_does_not_block_timer_and_errors_are_published(self):
        manager, calls = self.prepare()
        started, finish = threading.Event(), threading.Event()
        self.addCleanup(finish.set)
        def slow_apply(enabled):
            started.set()
            finish.wait(5)
            raise ValueError("fixture DNS unavailable")
        manager.integration.apply.side_effect = slow_apply
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.assertTrue(started.wait(2))
        self.assertTrue(self.request({"cmd": "status"})["websites"]["familyDns"]["applying"])
        self.parent(cmd="mode.set", mode="free")
        self.now += 1800
        self.daemon.refresh(self.now)
        self.lock_call.assert_called_once()
        finish.set(); self.wait(manager)
        self.daemon.refresh(self.now)
        status = self.request({"cmd": "status"})["websites"]["familyDns"]
        self.assertFalse(status["active"])
        self.assertEqual(status["error"], "fixture DNS unavailable")

    def test_reboot_and_disabling_last_enrollment(self):
        manager, calls = self.prepare()
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True})
        self.wait(manager)
        self.start_daemon()
        manager = self.daemon.services["school"].family_dns
        self.context.enter_context(patch.object(manager.integration, "apply", side_effect=lambda enabled: calls.append(enabled)))
        self.addCleanup(self.wait, manager)
        self.daemon.refresh(self.now); self.wait(manager)
        self.assertEqual(calls, [True, True])
        self.daemon.dispatch(0, {"scope": "school", "cmd": "users.set", "user": "linnea", "enabled": False})
        self.wait(manager)
        self.assertEqual(calls, [True, True, False])

    def test_failures_after_a_reload_back_off_and_a_new_choice_is_tried_at_once(self):
        manager, calls = self.prepare()
        clock = [1000.0]
        manager.monotonic = lambda: clock[0]
        outcome = [dns.Disrupted("fixture resolver mismatch")]
        def failing(enabled):
            calls.append(enabled)
            if enabled:
                raise outcome[0]
        manager.integration.apply.side_effect = failing
        def after(seconds):
            clock[0] += seconds
            self.daemon.refresh(self.now); self.wait(manager)
            return calls.count(True)
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True}); self.wait(manager)
        self.assertEqual(calls.count(True), 1)
        self.assertEqual(manager.status()["error"], "fixture resolver mismatch")
        self.assertEqual(after(29), 1)
        self.assertEqual(after(2), 2, "The first retry keeps the documented 30 seconds")
        self.assertIn("Trying again in 1 min; switch the toggle off and on", manager.status()["error"])
        self.assertEqual(after(45), 2, "Each reload restarts the resolver twice; do not repeat it twice a minute")
        self.assertEqual(after(20), 3)
        self.assertEqual(after(119), 3)
        self.assertEqual(after(2), 4)
        for _ in range(12):
            after(dns.RETRY_LIMIT + 1)
        self.assertIn("Trying again in 60 min", manager.status()["error"])
        # A conflict found before any change stays cheap, so it keeps the short interval.
        outcome[0] = ValueError("fixture conflict found beforehand")
        attempts = after(dns.RETRY_LIMIT + 1)
        self.assertEqual(manager.status()["error"], "fixture conflict found beforehand")
        self.assertEqual(after(31), attempts + 1)
        # Off and on again is the parent's retry button.
        outcome[0] = dns.Disrupted("fixture resolver mismatch")
        after(31)
        self.parent(cmd="config.patch", patch={"family_dns_enabled": False}); self.wait(manager)
        self.assertEqual(manager.status()["error"], "")
        attempts = calls.count(True)
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True}); self.wait(manager)
        self.assertEqual(calls.count(True), attempts + 1)
        self.assertEqual(manager.status()["error"], "fixture resolver mismatch")

    def test_an_unexpected_worker_failure_is_published_and_retried(self):
        manager, calls = self.prepare()
        clock = [1000.0]
        manager.monotonic = lambda: clock[0]
        def broken(enabled):
            calls.append(enabled)
            raise KeyError("fixture bug")
        manager.integration.apply.side_effect = broken
        self.parent(cmd="config.patch", patch={"family_dns_enabled": True}); self.wait(manager)
        status = self.request({"cmd": "status"})["websites"]["familyDns"]
        self.assertFalse(status["active"]); self.assertFalse(status["applying"])
        self.assertIn("stopped unexpectedly (KeyError", status["error"])
        clock[0] += 31
        self.daemon.refresh(self.now); self.wait(manager)
        self.assertEqual(calls, [True, True])


if __name__ == "__main__":
    unittest.main()
